version: '3'
services:
  app: &app-base
    build:
      context: .
      dockerfile: build/development.Dockerfile
      args:
        RAILS_ENV: development
    command: bundle exec rails server -b 0.0.0.0 -p '3000'
    ports:
      - '3000:3000'
    links:
      - postgres
    environment:
      LANG: 'C.UTF-8'
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: development
      SPRING_SOCKET: 'tmp/pids/spring.sock'
      SPRING_SERVER_COMMAND: 'build-compose up spring'
    env_file:
      - secrets.env
    volumes:
      - .:/rails_app
      - bundle-data:/usr/local/bundle
    stdin_open: true
    tty: true


  spring:
    <<: *app-base
    ports: []
    command: bundle exec spring server
    pid: host


  postgres:
    image: postgres:13.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  bundle-data: {}
  postgres-data: {}
