version: '3'
services:
  rails: &app-base
    build:
      context: .
      dockerfile: build/production.Dockerfile
      args:
        RAILS_ENV: production
    command: bundle exec rails server -b 0.0.0.0 -p '3000'
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      LANG: 'C.UTF-8'
      POSTGRES_HOST: db
      RAILS_ENV: production
    env_file:
      - secrets.env
    stdin_open: true
    tty: true


  db:
    image: postgres:13.1-alpine
    ports:
      - '5432:5432'
    environment:
      PGDATA: /var/lib/postgresql/data
    env_file:
      - secrets.env
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: {}
